-- =============================================================
-- Demo reviews seed (published) — MEMI Abbigliamento
-- Run AFTER the product catalog exists (products FK), e.g.:
--   docker exec -i <mysql-container> mysql -uroot -p<root_pw> memi_db < seed-reviews.sql
-- Idempotent-ish: deletes previous demo rows (by the demo email domain)
-- before inserting, so re-running never duplicates.
-- =============================================================
USE memi_db;

DELETE FROM reviews WHERE customer_email LIKE '%@demo.memi.it';

INSERT INTO reviews (product_id, product_name, customer_nome, customer_email, rating, titolo, testo, stato, risposta_admin, created_at) VALUES
('vestito-lino-cannes', 'Vestito Lino Cannes', 'Giulia R.', 'giulia.r@demo.memi.it', 5, 'Il vestito dell''estate', 'Lino freschissimo e la vestibilità è esattamente come in foto. Ho preso la S e cade perfetto. Lavato due volte, è ancora più morbido.', 'pubblicata', NULL, '2026-06-18 10:24:00'),
('vestito-lino-cannes', 'Vestito Lino Cannes', 'Martina C.', 'martina.c@demo.memi.it', 4, 'Bellissimo, vestibilità comoda', 'Colore delicato e tessuto di qualità. Unica nota: si stropiccia un po'' come tutti i lini, ma fa parte del suo fascino.', 'pubblicata', 'Grazie Martina! Un consiglio: appendilo in bagno durante la doccia, il vapore distende le pieghe del lino in modo naturale.', '2026-06-25 18:41:00'),
('vestito-lino-cannes', 'Vestito Lino Cannes', 'Alessia P.', 'alessia.p@demo.memi.it', 5, NULL, 'Comprato per un matrimonio in spiaggia, ho ricevuto complimenti tutta la sera. Spedizione rapidissima.', 'pubblicata', NULL, '2026-07-01 09:12:00'),
('blazer-sartoriale-mia', 'Blazer Sartoriale Mia', 'Francesca D.', 'francesca.d@demo.memi.it', 5, 'Qualità sartoriale vera', 'Si vede la mano artigianale: i revers cadono perfetti e la fodera è curata. Con lo sconto è un affare incredibile.', 'pubblicata', NULL, '2026-05-30 14:05:00'),
('blazer-sartoriale-mia', 'Blazer Sartoriale Mia', 'Elena V.', 'elena.v@demo.memi.it', 4, 'Elegante e versatile', 'Lo uso sia in ufficio che la sera. Il verde salvia è ancora più bello dal vivo. Taglia leggermente comoda, valutate di scendere.', 'pubblicata', NULL, '2026-06-12 20:33:00'),
('borsa-tote-lino', 'Borsa Tote Lino', 'Chiara M.', 'chiara.m@demo.memi.it', 5, 'La borsa perfetta per il lavoro', 'Entra tutto: laptop, agenda, pranzo. I manici in pelle sono robusti e il lino non si è deformato dopo un mese di uso quotidiano.', 'pubblicata', NULL, '2026-06-08 08:47:00'),
('borsa-tote-lino', 'Borsa Tote Lino', 'Sara B.', 'sara.b@demo.memi.it', 5, NULL, 'Regalo per mia sorella, è rimasta senza parole. Il dettaglio del portachiavi a moschettone è genialità pura.', 'pubblicata', NULL, '2026-06-28 16:19:00'),
('sneaker-tela-salvia', 'Sneaker Tela Salvia', 'Valentina T.', 'valentina.t@demo.memi.it', 5, 'Comodissime da subito', 'Nessun rodaggio, comode dal primo giorno. Il verde salvia sta bene con tutto. Apprezzo molto i materiali riciclati.', 'pubblicata', NULL, '2026-06-15 11:52:00'),
('sneaker-tela-salvia', 'Sneaker Tela Salvia', 'Roberta L.', 'roberta.l@demo.memi.it', 4, 'Belle e sostenibili', 'Calzata fedele al numero. Tolgo una stella solo perché con la pioggia la tela si bagna facilmente, ma d''estate sono perfette.', 'pubblicata', NULL, '2026-06-22 19:08:00'),
('gonna-plisse-nuvola', 'Gonna Plissé Nuvola', 'Ilaria F.', 'ilaria.f@demo.memi.it', 5, 'Si muove che è una meraviglia', 'Il plissé è di ottima qualità e non si stira mai, esce dalla valigia perfetto. Con il top bustier è un look da sera pronto.', 'pubblicata', NULL, '2026-06-19 21:15:00'),
('gonna-plisse-nuvola', 'Gonna Plissé Nuvola', 'Paola G.', 'paola.g@demo.memi.it', 4, NULL, 'Leggerissima e la vita elastica è comoda anche a cena :) Avrei gradito qualche colore in più.', 'pubblicata', 'Grazie Paola! In autunno arriva anche in verde muschio e cipria scuro — iscriviti alla newsletter per l''anteprima.', '2026-06-30 12:40:00'),
('top-seta-lucida-aria', 'Top Seta Lucida Aria', 'Camilla S.', 'camilla.s@demo.memi.it', 5, 'Seta vera, luce incredibile', 'Il taglio in sbieco fa la differenza: cade morbido senza segnare. Sotto il blazer è perfetto per l''ufficio.', 'pubblicata', NULL, '2026-06-10 09:30:00'),
('sandalo-listino-estate', 'Sandalo Listino Estate', 'Federica N.', 'federica.n@demo.memi.it', 5, 'Ore in piedi senza problemi', 'Il memory foam si sente: li ho messi a un matrimonio dalle 11 di mattina a mezzanotte. Pelle morbida che non ha fatto nemmeno una vescica.', 'pubblicata', NULL, '2026-06-05 17:26:00'),
('sandalo-listino-estate', 'Sandalo Listino Estate', 'Anna Z.', 'anna.z@demo.memi.it', 4, 'Eleganti e comodi', 'Molto belli, la fibbia dorata è un dettaglio raffinato. Consiglio di prendere il proprio numero abituale.', 'pubblicata', NULL, '2026-06-27 10:55:00'),
('collana-perla-aurora', 'Collana Perla Aurora', 'Beatrice K.', 'beatrice.k@demo.memi.it', 5, 'Le perle barocche sono splendide', 'Ogni perla è diversa e la collana prende luce in un modo unico. La porto anche al mare senza problemi.', 'pubblicata', NULL, '2026-06-21 15:37:00'),
('vestito-midi-fiori', 'Vestito Midi Fiori', 'Lucia E.', 'lucia.e@demo.memi.it', 5, 'La stampa è ancora più bella dal vivo', 'Micro-fiori delicatissimi, per niente banali. L''arricciatura in vita valorizza la silhouette. Perfetto per le cerimonie.', 'pubblicata', NULL, '2026-06-14 13:44:00'),
('vestito-midi-fiori', 'Vestito Midi Fiori', 'Silvia H.', 'silvia.h@demo.memi.it', 3, 'Bello ma lungo', 'Vestito di qualità, però sono 1.58 e mi arriva quasi alla caviglia. Con un tacco si risolve, ma tenetene conto se siete minute.', 'pubblicata', 'Grazie del feedback Silvia! Il capo è pensato per una lunghezza midi su statura 170 cm — il nostro servizio clienti può consigliarti un orlo sartoriale gratuito in negozio.', '2026-06-24 18:02:00'),
('camicia-cotone-brisa', 'Camicia Cotone Brisa', 'Marta W.', 'marta.w@demo.memi.it', 5, 'Il corallo è stupendo', 'Cotone organico che si sente al tatto, colore che illumina. Annodata in vita sui jeans è il mio look preferito.', 'pubblicata', NULL, '2026-06-17 08:21:00'),
('borsa-bucket-sabbia', 'Borsa Bucket Sabbia', 'Teresa Q.', 'teresa.q@demo.memi.it', 5, 'Un classico che vale ogni euro', 'La pelle è spessa e profumata, la coulisse scorre benissimo. Con lo sconto attuale è imperdibile. Arrivata con sacchetto antipolvere e biglietto scritto a mano.', 'pubblicata', NULL, '2026-06-26 22:10:00'),
('mocassino-pelle-soft', 'Mocassino Pelle Soft', 'Giovanna Y.', 'giovanna.y@demo.memi.it', 4, 'Morbidissimi', 'Pelle burro, davvero soft come dice il nome. Primi due giorni leggermente rigidi sul tallone, poi perfetti.', 'pubblicata', NULL, '2026-06-11 16:48:00');
